# Generated by Django 2.2.1 on 2019-05-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190516_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='cover',
            new_name='image',
        ),
    ]
